@echo off
echo Starting Hotel Booking Project...

echo Starting MySQL from XAMPP...
start /B "" "C:\xampp\mysql\bin\mysqld.exe"

echo Starting backend server...
start "Backend Server" cmd /k "node backend/server.js"

echo Waiting for services to initialize...
timeout /t 5 /nobreak > nul

echo Opening frontend application...
start index.html
